#!/bin/bash
### BEGIN INIT INFO
# Provides: monitoritzar_logs
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Aquest servei escriu missatges d'error d'un servei a un log.
### END INIT INFO
PATH=/bin:/sbin:/usr/bin:/usr/sbin
SERVICE_SCRIPT="/home/GSX/monitoritzar_logs.sh"
PIDFILE="/var/run/monitoritzar_logs.pid"
LOGFILE="/var/log/monitoritzar_logs.log"
case "$1" in
    start)
        echo "Iniciant monitoritzar_logs..."
        if [ -f $PIDFILE ]; then
            echo "El servei ja està actiu."
            exit 1
        fi
        nohup $SERVICE_SCRIPT >> $LOGFILE 2>&1 &
        echo $! > $PIDFILE
        echo "monitoritzar_logs iniciat."
        ;;
    stop)
        echo "Aturant monitoritzar_logs..."
        if [ ! -f $PIDFILE ]; then
            echo "El servei no està actiu."
            exit 2
        fi
        kill $(cat $PIDFILE) && rm -f $PIDFILE
        echo "monitoritzar_logs aturat."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ]; then
            echo "monitoritzar_logs està actiu (PID: $(cat $PIDFILE))."
        else
            echo "monitoritzar_logs no està actiu."
        fi
        ;;
    *)
    echo "Ús: $0 {start|stop|restart|status}"
    exit 3
    ;;
esac
exit 0
