#!/bin/bash

# Creación del gupo techsoft
if ! getent group techsoft >/dev/null; then
    sudo groupadd techsoft
fi

USERS=("dev1" "dev2" "dev3")
GROUP=techsoft

# Creación de la carpeta del grupo junto con sus permisos
sudo mkdir -p /home/techsoft
sudo chgrp techsoft /home/techsoft
sudo chmod 775 /home/techsoft

# Crear entorno para cada usuario
for usuario in "${USERS[@]}";do
        if ! getent group $GROUP | grep -q $usuario;then
                # Crear usuarios junto a sus cartpeas
                sudo useradd -m -s /bin/bash -d "/home/$GROUP/$usuario" -G "$GROUP" "$usuario"
	fi
done


# Para guardar programas y scripts, solo el grupo techsoft puede escribir
sudo mkdir -p /home/techsoft/bin
sudo chown :techsoft /home/techsoft/bin
sudo chmod 2770 /home/techsoft/bin

# Compartir archivos del grupo techsoft contra protección de borrados (SGID bit)
sudo mkdir -p /home/techsoft/shared
sudo chown :techsoft /home/techsoft/shared
sudo chmod 1770 /home/techsoft/shared

# Creación del archivo fet.log perteneciente al usuario dev1
sudo touch /home/techsoft/fet.log
sudo chown dev1:techsoft /home/techsoft/fet.log
sudo chmod 640 /home/techsoft/fet.log

# Informació
echo ""
getent group "$GROUP"

echo ""
for user in "${USERS[@]}";do
	groups "$user"
done

echo ""
ls -l "/home/$GROUP"

echo ""
if [ -f afegir_fet.c ]; then
	echo "Ejecución afegir_fet.c"
	sudo chmod 744 afegir_fet.c
	sudo gcc afegir_fet.c -o afegir_fet

	echo -e "\n -Test con Dev1"
	sudo -u dev1 ./afegir_fet "Mensaje Pruebas"
	sudo cat /home/techsoft/fet.log

	echo -e "\n -Test con Dev3"
	sudo -u dev3 ./afegir_fet "Mensaje de Error"
else
	echo "Archivo afegir_fet.c no encontrado en la carpeta actual de ejecución"
fi

# Configuración limites ulimit
cat << 'EOF' | sudo tee /etc/profile.d/techsoft_limits.sh > /dev/null
#!/bin/bash
# If user is assigned to techsoft group, apply limits
if id -nG "$USER" | grep -qw techsoft; then
    ulimit -u 100       # Maximum processes
    ulimit -n 2048      # Maximum opened files
fi
EOF
sudo chmod +x /etc/profile.d/techsoft_limits.sh

# Configurar los límites de uso
if ! grep -q "^@techsoft	soft	nproc		50$" /etc/security/limits.conf ;then
	echo "@techsoft	soft	nproc		50" | sudo tee -a /etc/security/limits.conf
fi
if ! grep -q "^@techsoft	hard	nproc		50$" /etc/security/limits.conf ;then
	echo "@techsoft	hard	nproc		50" | sudo tee -a /etc/security/limits.conf
fi
if ! grep -q "^@techsoft	soft	as		1048576$" /etc/security/limits.conf ;then
	echo "@techsoft	soft	as		1048576" | sudo tee -a /etc/security/limits.conf
fi
if ! grep -q "^@techsoft	hard	as		1048576$" /etc/security/limits.conf ;then
	echo "@techsoft	hard	as		1048576" | sudo tee -a /etc/security/limits.conf
fi

echo -e "\nTEST LIMITES Ulimits"
echo -e "- Cat limits.conf:"
cat /etc/security/limits.conf | tail -10

if ! grep -q "hope you have a nice day" /etc/profile;then
sudo tee -a /etc/profile > /dev/null << 'EOF'
if id -nG "$USER" | grep -qw techsoft; then
        echo "****************************"
        echo "Welcome $USER, hope you have a nice day!"
        echo "****************************"
fi
EOF
fi

sudo tee -a /etc/profile.d/techsoft.sh > /dev/null << 'EOF'
#!/bin/bash

# If user is on techsoft group, add /home/techsoft/bin to PATH
if id -nG "$USER" | grep -qw techsoft; then
    export PATH="$PATH:/home/techsoft/bin"
fi
EOF






echo -e "\n- Test por Usuario"

echo "milax:"
sudo -u milax bash -c 'echo "nproc : $(ulimit -u)"; echo "nofile: $(ulimit -n)"'
echo ""
echo "Dev1:"
sudo -u dev1 bash -c 'echo "nproc : $(ulimit -u)"; echo "nofile: $(ulimit -n)"'
echo "Dev2:"
sudo -u dev2 bash -c 'echo "nproc : $(ulimit -u)"; echo "nofile: $(ulimit -n)"'
echo "Dev3:"
sudo -u dev3 bash -c 'echo "nproc : $(ulimit -u)"; echo "nofile: $(ulimit -n)"'


echo -e "\nTEST LIMITES PAM"







